---
apiVersion: v1
kind: Service
metadata:
  name: kv-store-service
spec:
  type: NodePort
  ports:
  - port: 8080
    name: web
    targetPort: 8080
    nodePort: 30911
  selector:
    app: kv-store
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kv-store
spec:
  serviceName: "kv-store-service"
  replicas: 1
  selector:
    matchLabels:
      app: kv-store
  template:
    metadata:
      labels:
        app: kv-store
    spec:
      containers:
      - name: kv-store
        image: cpp-k8s-kv-store:v4
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
          name: web
        volumeMounts:
        - name: wal-storage
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: wal-storage
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 100Mi